[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/imagekit-auth"
  to = "/.netlify/functions/imagekit-auth"
  status = 200

[[redirects]]
  from = "/api/send-team-assignment"
  to = "/.netlify/functions/send-team-assignment"
  status = 200

[[redirects]]
  from = "/api/send-match-schedule"
  to = "/.netlify/functions/send-match-schedule"
  status = 200
